import { createRouter, createWebHistory } from 'vue-router'
import HomeView from '../views/HomeView.vue'

const router = createRouter({
  history: createWebHistory(),
  routes: [
    { path: '/', name: 'home', component: HomeView },
    { path: '/login', name: 'login', component: () => import('../views/AuthView.vue') },
    { path: '/compose', name: 'compose', component: () => import('../views/ComposeView.vue') },
    { path: '/user/:id', name: 'profile', component: () => import('../views/ProfileView.vue') },
    { path: '/user/:id/following', name: 'profile-following', component: () => import('../views/FollowListView.vue'), props: { tab: 'following' } },
    { path: '/user/:id/followers', name: 'profile-followers', component: () => import('../views/FollowListView.vue'), props: { tab: 'followers' } },
    { path: '/user/:id/favorites', name: 'profile-favorites', component: () => import('../views/FavoritesView.vue') },
    { path: '/post/:id', name: 'post', component: () => import('../views/PostView.vue') },
    { path: '/admin/reports', name: 'admin-reports', component: () => import('../views/AdminReportsView.vue') },
    { path: '/galgame', name: 'galgame', component: () => import('../views/GalgameView.vue') },
    { path: '/galgame/new', name: 'galgame-new', component: () => import('../views/AddGalgameView.vue') },
    { path: '/galgame/review', name: 'galgame-review', component: () => import('../views/GalgameReviewView.vue') },
    { path: '/galgame/edit-staffs', name: 'galgame-edit-staffs', component: () => import('../views/GalgameLinksEditorView.vue'), props: { type: 'staffs' } },
    { path: '/galgame/edit-characters', name: 'galgame-edit-characters', component: () => import('../views/GalgameLinksEditorView.vue'), props: { type: 'characters' } },
    { path: '/galgame/mine', name: 'galgame-mine', component: () => import('../views/GalgameMineView.vue') },
    { path: '/galgame/tag', name: 'galgame-tag', component: () => import('../views/GalgameTagView.vue') },
    { path: '/galgame/tag/:id', name: 'galgame-tag-detail', component: () => import('../views/GalgameTagDetailView.vue') },
    { path: '/galgame/:id', name: 'galgame-detail', component: () => import('../views/GalgameDetailView.vue') },
    { path: '/galgame/:id/contributors', name: 'galgame-contributors', component: () => import('../views/EntityContributorsView.vue') },
    { path: '/company', name: 'company', component: () => import('../views/CompanyView.vue') },
    { path: '/company/new', name: 'company-new', component: () => import('../views/AddCompanyView.vue') },
    { path: '/company/review', name: 'company-review', component: () => import('../views/CompanyReviewView.vue') },
    { path: '/company/mine', name: 'company-mine', component: () => import('../views/CompanyMineView.vue') },
    { path: '/company/:id', name: 'company-detail', component: () => import('../views/CompanyDetailView.vue') },
    { path: '/company/:id/contributors', name: 'company-contributors', component: () => import('../views/EntityContributorsView.vue') },
    { path: '/staff', name: 'staff', component: () => import('../views/StaffView.vue') },
    { path: '/staff/new', name: 'staff-new', component: () => import('../views/AddStaffView.vue') },
    { path: '/staff/review', name: 'staff-review', component: () => import('../views/StaffReviewView.vue') },
    { path: '/staff/mine', name: 'staff-mine', component: () => import('../views/StaffMineView.vue') },
    { path: '/staff/:id', name: 'staff-detail', component: () => import('../views/StaffDetailView.vue') },
    { path: '/staff/:id/contributors', name: 'staff-contributors', component: () => import('../views/EntityContributorsView.vue') },
    { path: '/character', name: 'character', component: () => import('../views/CharacterView.vue') },
    { path: '/character/new', name: 'character-new', component: () => import('../views/AddCharacterView.vue') },
    { path: '/character/review', name: 'character-review', component: () => import('../views/CharacterReviewView.vue') },
    { path: '/character/mine', name: 'character-mine', component: () => import('../views/CharacterMineView.vue') },
    { path: '/character/:id', name: 'character-detail', component: () => import('../views/CharacterDetailView.vue') },
    { path: '/character/:id/contributors', name: 'character-contributors', component: () => import('../views/EntityContributorsView.vue') },
    { path: '/tag/:category', name: 'tag-category', component: () => import('../views/SectionView.vue') },
    { path: '/tag/:category/:section', name: 'tag-section', component: () => import('../views/SectionView.vue') },
    { path: '/search-user', name: 'search-user', component: () => import('../views/SearchUserView.vue') },
    { path: '/user-ranking', name: 'user-ranking', component: () => import('../views/UserRankingView.vue') },
    { path: '/messages', name: 'messages', component: () => import('../views/MessagesView.vue') },
    { path: '/messages/:userId', name: 'conversation', component: () => import('../views/ConversationView.vue') },
  ],
})

export default router
